name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install -g @nestjs/cli @angular/cli
      - name: Build Backend
        run: cd backend && npm install && npm run build
      - name: Build Frontend
        run: cd frontend && npm install && npm run build